package hook

const (
	HOOK_PLAYER_INITIALIZED = iota
	HOOK_RESULT_FETCH_STARTED
	HOOK_FILE_LOAD_STARTED
	HOOK_FILE_LOADED
	HOOK_FILE_ENDED
	HOOK_FILE_APPENDED
	HOOK_PLAYBACK_PAUSED
	HOOK_PLAYBACK_RESUMED
	HOOK_VOLUME_CHANGED
	HOOK_POSITION_CHANGED
	HOOK_RESULT_DOWNLOAD_STARTED
	HOOK_QUEUE_UPDATE_FINISHED
	HOOK_PLAYER_EXIT
	HOOK_LOOP_STATUS_CHANGED

	HOOK_GUI_STARTED

	// communicate the tray with the gtk window
	HOOK_REQUEST_EXIT
	HOOK_REQUEST_SHOW_HIDE
)
